export enum ErrorCode {
  BAD_USER_INPUT = "BAD_USER_INPUT",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  ACCESS_DENIED = "ACCESS_DENIED",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
